### PR TITLE
Improve modman file to avoid duplicate files when installing with composer.

### PR DESCRIPTION
**Pull request by janpapenbrock**
Before, tree looked like

```
app/code/community/Cm/RedisSession/
  - code/
    - etc/config.xml
    - Model/Session.php
 - etc/config.xml
 - Model/Session.php
```

After, tree looks like

```
app/code/community/Cm/RedisSession/
 - etc/config.xml
 - Model/Session.php
```

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Sounds like a composer bug or user error to me.. app/code/community/Cm/RedisSession should not exist unless it was a symlink that was created by modman (or similar) in which case modman will not produce the result you show in the Before example. Can you describe what steps you went through to get this issue?

**Comment by janpapenbrock** [comment]
Oh, I forgot we probably have this special edge case...

In `composer.json` we use

```
"extra": {
        "magento-root-dir":        ".",
        "magento-deploystrategy":  "copy",
        "skip-package-deployment": false,
        "magento-force":           true
    }
```

**Comment by janpapenbrock** [comment]
I used [this modman file of Ecomdev](https://github.com/EcomDev/EcomDev_PHPUnit/blob/master/modman) as a reference.

**Comment by colinmollenhour** [comment]
It is my opinion that this issue is with the deploy tools and not the modman file since the modman file is perfectly valid. The deploy tools should be completely idempotent, except for when switching from copy to symlink mode or vice versa which is highly problematic and IMO should not be a supported action.

**Pull request closed without merging**
