### PR TITLE
Sync XML module version

### PR DESCRIPTION
**Pull request by loekvangool**

### CODE REVIEW

**Comment by fballiano** [comment]
I think this should be merged

**Comment by colinmollenhour** [comment]
Why does the xml module version matter if there are no database migrations? It seem sit would just create busy-work when updating packages?

**Comment by loekvangool** [comment]
Makes it easier to match latest and installed versions.

**Comment by colinmollenhour** [comment]
I think composer is a much better tool for this purpose though?

**Comment by loekvangool** [comment]
The bulk of Magento modules that I use don't support composer, hence I don't use it for managing modules atm. I use [Firegento ](https://github.com/firegento/firegento-debug) to get a list of installed modules and their versions and I compare to the latest available versions to start my upgrade process.

**Comment by colinmollenhour** [comment]
I appreciate that different people have different methods and I try to accommodate them but in this case I must decline. In my opinion the version number of a library release belongs outside of the source code, changing version numbers for every point release (basically every PR for this project) is just unnecessary hassle. The Magento module version number is very useful for the database migrations and may have been worthwhile in the days of Magento Connect but that is no more and Github releases + Packagist ++ Composer is a solid system that I highly recommend adopting (and this is coming from the author of modman 😄 ).

**Pull request closed without merging**
