### PR TITLE
GitHub 127 installs into app code local cm redis session code

### PR DESCRIPTION
**Pull request by kirkmadera**
Most modules are now structured like this where the path matches the target path. I think the only real requirement is that the final filename matches the existing one for it to now make a new subdirectory, however, this is the most common approach for M1 modules.

### CODE REVIEW

**Comment by kirkmadera** [comment]
Resolves #127

**Comment by colinmollenhour** [comment]
This seems like a reasonable change. I'll try to test it out soon.

Thanks!

**Comment by kirkmadera** [comment]
Ii just thought about this also. This change could be a good opportunity to switch from app/code/local to app/code/community also.

**Comment by seansan** [comment]
@kirkmadera - If this is merged + moved to community then adding some kind of simple PHP script to remove the old files wouold be nice. Reason 1: it makes it simple. But IK ave learnt reason 2: people see the file and are made more aware of the move in codepool.

**Comment by colinmollenhour** [comment]
Merged and tagged as 2.2.0

**Pull request merged**
