### PR TITLE
Minor fix for deploying in an already copied/existing directory

### PR DESCRIPTION
**Pull request by TimVroom**
Putting the trail on the end it enforces to install it to a proper directory instead of appending code to the RedisSession dir. (fixed it for me)
Especially for composer installs

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Seems like a bug in composer installer..

**Comment by TimVroom** [comment]
Quite possible, but with i only have this problem with this module, so thought i fix it here. And this fixed it for me.

But should go to the composer installer module then.

**Comment by colinmollenhour** [comment]
modman checks if the target is a directory and it if is then treats it the same as ending with a / so I'm guessing composer installer does not do this.

**Comment by andrey-legayev** [comment]
I tried to merge this pull request, but it didn't resolve the issue. Composer installer keeps creating RedisSession/code/...

**Comment by colinmollenhour** [comment]
I think this is fixed now in 2.2.0

**Pull request closed without merging**
